FROM node:14-alpine
RUN mkdir /app
WORKDIR /app

EXPOSE 3001
EXPOSE 3306

COPY package*.json /app/

RUN npm install

COPY dist /app/

CMD [ "npm run start:dev" ]
ENTRYPOINT [ "sh", "-c" ]