version: '3'
networks:
  store_app:
    external: true
volumes:
  db:
    driver: local

services:
  store_app:
    container_name: store_app
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    ports:
      - 3001:3000
    env_file:
      - .env
    networks:
      - store_app
    depends_on:
      - store_db

  store_db:
    image: mysql:5.7
    container_name: store_db
    networks:
      - store_app
    ports:
      - '3306:3306'
    volumes:
      - './data/store_app:/docker-entrypoint-initdb.d'
      - 'db:/var/lib/mysql'
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password  --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
